export interface Transaction {
    id: string;
    email: string;
    dateTime: string;
    type: string;
    amount: number;
    transactionId: string;
}

export const transactionsData: Transaction[] = [
    {
        id: "1",
        email: "john.smith@gmail.com",
        dateTime: "12 March - 2:10 Pm",
        type: "Money Received",
        amount: 5000.0,
        transactionId: "#pay-2024-001",
    },
    {
        id: "2",
        email: "oliyben@gmail.com",
        dateTime: "12 March - 2:10 Pm",
        type: "Money Received",
        amount: 2450.0,
        transactionId: "#pay-2024-001",
    },
    {
        id: "3",
        email: "dwarren3@gmail.com",
        dateTime: "12 March - 2:10 Pm",
        type: "Money Received",
        amount: 5000.0,
        transactionId: "#pay-2024-001",
    },
    {
        id: "4",
        email: "chloehyee@gmail.com",
        dateTime: "12 March - 2:10 Pm",
        type: "Money Received",
        amount: 5000.0,
        transactionId: "#pay-2024-001",
    },
    {
        id: "5",
        email: "reeds777@gmail.com",
        dateTime: "12 March - 2:10 Pm",
        type: "Money Received",
        amount: 5000.0,
        transactionId: "#pay-2024-001",
    },
    {
        id: "6",
        email: "belleclark@gmail.com",
        dateTime: "12 March - 2:10 Pm",
        type: "Money Received",
        amount: 5000.0,
        transactionId: "#pay-2024-001",
    },
    {
        id: "7",
        email: "lucamich@gmail.com",
        dateTime: "12 March - 2:10 Pm",
        type: "Money Received",
        amount: 5000.0,
        transactionId: "#pay-2024-001",
    },
    {
        id: "8",
        email: "markwill32@gmail.com",
        dateTime: "12 March - 2:10 Pm",
        type: "Money Received",
        amount: 5000.0,
        transactionId: "#pay-2024-001",
    },
    {
        id: "9",
        email: "nicolass009@gmail.com",
        dateTime: "12 March - 2:10 Pm",
        type: "Money Received",
        amount: 5000.0,
        transactionId: "#pay-2024-001",
    },
    {
        id: "10",
        email: "mianaddin@gmail.com",
        dateTime: "12 March - 2:10 Pm",
        type: "Money Received",
        amount: 5000.0,
        transactionId: "#pay-2024-001",
    },
    {
        id: "11",
        email: "noemivill99@gmail.com",
        dateTime: "12 March - 2:10 Pm",
        type: "Money Received",
        amount: 5000.0,
        transactionId: "#pay-2024-001",
    },
    {
        id: "12",
        email: "noemivill99@gmail.com",
        dateTime: "12 March - 2:10 Pm",
        type: "Money Received",
        amount: 5000.0,
        transactionId: "#pay-2024-001",
    },
    {
        id: "13",
        email: "noemivill99@gmail.com",
        dateTime: "12 March - 2:10 Pm",
        type: "Money Received",
        amount: 5000.0,
        transactionId: "#pay-2024-001",
    },
    {
        id: "14",
        email: "noemivill99@gmail.com",
        dateTime: "12 March - 2:10 Pm",
        type: "Money Received",
        amount: 5000.0,
        transactionId: "#pay-2024-001",
    },
    {
        id: "15",
        email: "noemivill99@gmail.com",
        dateTime: "12 March - 2:10 Pm",
        type: "Money Received",
        amount: 5000.0,
        transactionId: "#pay-2024-001",
    },
    {
        id: "16",
        email: "noemivill99@gmail.com",
        dateTime: "12 March - 2:10 Pm",
        type: "Money Received",
        amount: 5000.0,
        transactionId: "#pay-2024-001",
    },
    {
        id: "17",
        email: "noemivill99@gmail.com",
        dateTime: "12 March - 2:10 Pm",
        type: "Money Received",
        amount: 5000.0,
        transactionId: "#pay-2024-001",
    },
    {
        id: "18",
        email: "noemivill99@gmail.com",
        dateTime: "12 March - 2:10 Pm",
        type: "Money Received",
        amount: 5000.0,
        transactionId: "#pay-2024-001",
    },
    {
        id: "19",
        email: "noemivill99@gmail.com",
        dateTime: "12 March - 2:10 Pm",
        type: "Money Received",
        amount: 5000.0,
        transactionId: "#pay-2024-001",
    },
    {
        id: "20",
        email: "noemivill99@gmail.com",
        dateTime: "12 March - 2:10 Pm",
        type: "Money Received",
        amount: 5000.0,
        transactionId: "#pay-2024-001",
    },
];
