export interface Customer {
    id: string;
    fullName: string;
    email: string;
    phone: string;
    address: string;
    status: "Paid" | "Unpaid" | "—";
}

export const customerData: Customer[] = [
    {
        id: "1",
        fullName: "John Smith",
        email: "john.smith@gmail.com",
        phone: "01736591645",
        address: "Dhaka, Bangladesh",
        status: "Paid",
    },
    {
        id: "2",
        fullName: "Olivia Bennett",
        email: "olivyben@gmail.com",
        phone: "01736591645",
        address: "Dhaka, Bangladesh",
        status: "Unpaid",
    },
    {
        id: "3",
        fullName: "Daniel Warren",
        email: "dwarren3@gmail.com",
        phone: "01736591645",
        address: "Dhaka, Bangladesh",
        status: "—",
    },
    {
        id: "4",
        fullName: "Chloe Hayes",
        email: "chloehayesn@gmail.com",
        phone: "01736591645",
        address: "Dhaka, Bangladesh",
        status: "Unpaid",
    },
    {
        id: "5",
        fullName: "Marcus Reed",
        email: "reeds777@gmail.com",
        phone: "01736591645",
        address: "Dhaka, Bangladesh",
        status: "Paid",
    },
    {
        id: "6",
        fullName: "Isabelle Clark",
        email: "belleclark@gmail.com",
        phone: "01736591645",
        address: "Dhaka, Bangladesh",
        status: "Unpaid",
    },
    {
        id: "7",
        fullName: "Lucas Mitchell",
        email: "lucamitch@gmail.com",
        phone: "01736591645",
        address: "Dhaka, Bangladesh",
        status: "Paid",
    },
    {
        id: "8",
        fullName: "Mark Wilburg",
        email: "markwill32@gmail.com",
        phone: "01736591645",
        address: "Dhaka, Bangladesh",
        status: "—",
    },
    {
        id: "9",
        fullName: "Nicholas Agenn",
        email: "nicolass009@gmail.com",
        phone: "01736591645",
        address: "Dhaka, Bangladesh",
        status: "Paid",
    },
    {
        id: "10",
        fullName: "Mia Nadinn",
        email: "mianaddin@gmail.com",
        phone: "01736591645",
        address: "Dhaka, Bangladesh",
        status: "Unpaid",
    },
    {
        id: "11",
        fullName: "Noemi Villan",
        email: "noemivill99@gmail.com",
        phone: "01736591645",
        address: "Dhaka, Bangladesh",
        status: "Paid",
    },
    {
        id: "12",
        fullName: "Noemi Villan",
        email: "noemivill99@gmail.com",
        phone: "01736591645",
        address: "Dhaka, Bangladesh",
        status: "Unpaid",
    },
    {
        id: "13",
        fullName: "Noemi Villan",
        email: "noemivill99@gmail.com",
        phone: "01736591645",
        address: "Dhaka, Bangladesh",
        status: "Paid",
    },
    {
        id: "14",
        fullName: "Noemi Villan",
        email: "noemivill99@gmail.com",
        phone: "01736591645",
        address: "Dhaka, Bangladesh",
        status: "Unpaid",
    },
    {
        id: "15",
        fullName: "Noemi Villan",
        email: "noemivill99@gmail.com",
        phone: "01736591645",
        address: "Dhaka, Bangladesh",
        status: "—",
    },
    {
        id: "16",
        fullName: "Noemi Villan",
        email: "noemivill99@gmail.com",
        phone: "01736591645",
        address: "Dhaka, Bangladesh",
        status: "Unpaid",
    },
    {
        id: "17",
        fullName: "Noemi Villan",
        email: "noemivill99@gmail.com",
        phone: "01736591645",
        address: "Dhaka, Bangladesh",
        status: "Paid",
    },
    {
        id: "18",
        fullName: "Noemi Villan",
        email: "noemivill99@gmail.com",
        phone: "01736591645",
        address: "Dhaka, Bangladesh",
        status: "Unpaid",
    },
];
